<a href="https://colab.research.google.com/github/amitdeo28/Pytorch-/blob/main/Pythorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

## **TENSORS**



*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to numpy array
*   default data type float32
*   More suitable for deep learning than a numpy array



In [85]:
import torch
import numpy as np

## **LISTS**

In [86]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## **Numpy Array**

In [87]:
np = np.random.rand(3, 4)
np

array([[0.14332621, 0.06849183, 0.27527777, 0.83634006],
       [0.55907942, 0.75129682, 0.4011586 , 0.1508728 ],
       [0.24034644, 0.17472496, 0.7352933 , 0.35151752]])

In [88]:
np.dtype

dtype('float64')

## **Tensors**

In [89]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.5434,  0.0904, -2.8272, -0.1534],
        [-0.2882,  1.2897,  0.4517,  0.3483],
        [ 0.5391, -0.9904, -0.0863,  0.9571]])

In [90]:
tensor_2d.dtype

torch.float32

In [91]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [92]:
# create tensor out of numpy array
my_tensor = torch.tensor(np)
my_tensor

tensor([[0.1433, 0.0685, 0.2753, 0.8363],
        [0.5591, 0.7513, 0.4012, 0.1509],
        [0.2403, 0.1747, 0.7353, 0.3515]], dtype=torch.float64)

In [93]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# Reshape and View
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [95]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [97]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [99]:
# with reshape and view , they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [101]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [102]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [103]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
# Grab a specific item
my_torch7[5]

tensor(5)

In [105]:
# Grab and Slice
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [106]:
my_torch8[:, 1]

tensor([1, 3, 5, 7, 9])

In [107]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## **Tensors Maths Oerations**



*   Add, subtract, multiply, divide, remainder, exponents
*   Shorthand and uh, Longhand
*   Reassingment



In [108]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [109]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [110]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [111]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [112]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [113]:
# Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [114]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [115]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [116]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [117]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [118]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [119]:
# Remainder longhead
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [120]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [122]:
# Reassingment
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [123]:
tensor_a

tensor([ 6,  8, 10, 12])